#!/usr/bin/env python
"""Compute the findings artifact and render docs/FINDINGS.md from it (ADR-0013 items 5, 6).

    python scripts/findings.py [--db .duckdb/dev.duckdb] [--check]

--check re-renders from the committed findings artifact and fails if docs/FINDINGS.md differs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import duckdb

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ev_charging_data_unified_schema.config import ARTIFACTS_DIR, REPO_ROOT  # noqa: E402
from ev_charging_data_unified_schema.findings import compute, run_id  # noqa: E402
from ev_charging_data_unified_schema.profiling import git_commit  # noqa: E402

OUT = REPO_ROOT / "docs" / "FINDINGS.md"
CITE = "artifacts/findings/latest.json"


def latest(kind: str) -> dict[str, Any]:
    d = ARTIFACTS_DIR / kind
    return json.loads((d / json.loads((d / "latest.json").read_text())["path"]).read_text())


def pct(x: float | None, d: int = 1) -> str:
    return "n/a" if x is None else f"{100 * x:.{d}f}%"


def n(x: Any) -> str:
    return f"{x:,}" if isinstance(x, int) else f"{x:,.0f}"


def cite(*keys: str) -> str:
    return "<!-- cite: " + "; ".join(f"{CITE}#{k}" for k in keys) + " -->"


def render(a: dict[str, Any]) -> str:
    p = a["periods"]
    idle = a["boulder_idle"]["production"]
    alts = {k: a["boulder_idle"][k] for k in sorted(a["boulder_idle"]) if k != "production"}
    b_lo = min(v["blocking_idle_share_of_connected"] for v in alts.values())
    b_hi = max(v["blocking_idle_share_of_connected"] for v in alts.values())
    hours = a["boulder_idle_by_hour_production"]
    top_hours = sorted(hours, key=lambda r: -r["blocking_idle_minutes"])[:3]
    ur = a["utilization_ranges"]
    pr = a["dft_publisher_rule"]
    decomp = pr["rapids_anomalies_not_meeting_rule"]
    rapids = pr["by_family"]["rapids"]
    ranom = pr["by_family"]["rapids_anomalies"]
    unknown = a["unknown_station"]["dft_2017"]
    lines = [
        "# Findings",
        "",
        f"_Generated by `scripts/findings.py` from `artifacts/findings/{a['run_id']}.json` (code commit `{a['code_commit'][:12]}`, "
        f"inputs: sensitivity `{a['inputs']['sensitivity_run_id']}`, silver summary `{a['inputs']['silver_run_id']}`). "
        "Every number is read from that artifact; the key follows each sentence in an HTML comment. Do not edit by hand._",
        "",
        "## Read this first: the sources do not share a period",
        "",
        "The three sources cover different years and countries, and each is one operator or one funding programme. "
        "Nothing below compares one source with another; every finding is within a source and states its period.",
        "",
        "| Source | First session (local) | Last session (local) | Sessions in the fact |",
        "|---|---|---|---|",
    ]
    for s in ("boulder", "cary", "dft_2017"):
        lines.append(
            f"| {s} | {p[s]['first_start_local'][:10]} | {p[s]['last_start_local'][:10]} | {n(p[s]['sessions'])} |"
        )
    # the citation sits directly under the table (no blank line) so the checker reads the table
    # and the comment as one unit
    lines.append(
        "<!-- cite: "
        + "; ".join(f"{CITE}#periods.{s}.sessions" for s in ("boulder", "cary", "dft_2017"))
        + " -->"
    )
    lines += [
        "",
        "What the data cannot show, for every finding:",
        "",
        *[f"- {c}" for c in a["cannot_show"]],
        "",
        "## 1. Boulder: idle-after-charge time is large; about a quarter of it blocks another driver",
        "",
        f"**Period.** Boulder, {p['boulder']['first_start_local'][:10]} to {p['boulder']['last_start_local'][:10]}, non-trivial sessions at known stations.",
        "",
        f"**What was found.** Over {n(idle['connected_minutes'])} connected minutes, {n(idle['idle_minutes'])} were idle after charging ended: "
        f"an idle share of {pct(idle['idle_share_of_connected'])}. "
        f"{cite('boulder_idle.production.connected_minutes', 'boulder_idle.production.idle_minutes', 'boulder_idle.production.idle_share_of_connected')} "
        f"Of those idle minutes, {n(idle['blocking_idle_minutes'])} elapsed while every inferred port at the station was occupied: "
        f"a blocking idle share of {pct(idle['blocking_idle_share_of_connected'])} of connected time, or {pct(idle['blocking_share_of_idle'])} of idle time, "
        f"and every one of the {idle['stations']} stations has some. "
        f"{cite('boulder_idle.production.blocking_idle_minutes', 'boulder_idle.production.blocking_idle_share_of_connected', 'boulder_idle.production.blocking_share_of_idle', 'boulder_idle.production.stations')} "
        f"The blocking share of connected time ranges from {pct(b_lo)} to {pct(b_hi)} across the robust-max port definitions (N = 1 to 10). "
        + "<!-- cite: "
        + "; ".join(f"{CITE}#boulder_idle.{k}.blocking_idle_share_of_connected" for k in alts)
        + " --> "
        f"Blocking idle is a midday phenomenon: local hours {', '.join(str(h['hour']) for h in top_hours)} carry the most of it. "
        + "<!-- cite: "
        + "; ".join(f"{CITE}#boulder_idle_by_hour_production[{h['hour']}].hour" for h in top_hours)
        + " -->",
        "",
        "**Why it matters.** The headline idle share is the number that usually gets quoted as recoverable capacity. "
        "On this data it overstates the part a policy could recover by about four times: most idle minutes happen while another port at the same station is free, "
        "so no driver was blocked by them. The blocking part is still substantial and happens at every station, at midday, when demand peaks.",
        "",
        "**What I would tell the decision-maker.** Lead with the blocking share. An idle fee or a time limit could recover at most the blocking minutes, "
        "and they cluster between late morning and mid-afternoon; a time-of-day rule would target most of the recoverable minutes without touching overnight idling, "
        "which blocks nobody.",
        "",
        "**What would change my mind.** Evidence that ports are undercounted at the busy stations would lower the blocking share (the sensitivity range shows how far); "
        "evidence of queues or turned-away drivers (not in the data) would raise the value of each blocking minute. "
        "Charging is assumed to begin at session start; if drivers plug in and charging starts later, some 'idle' minutes were charging.",
        "",
        "## 2. UK DfT 2017: the published exclusion rule does not describe the published exclusions",
        "",
        "**Period.** Calendar 2017, one year, one funding programme.",
        "",
        f"**What was found.** The publisher states one exclusion rule: zero energy or a plug-in of three minutes or less. "
        f"Applying it to the accepted rows of the rapids anomalies file marks {n(ranom['meets_rule'])} of {n(ranom['accepted'])} rows; "
        f"the rest do not meet the stated rule. {cite('dft_publisher_rule.by_family.rapids_anomalies.meets_rule', 'dft_publisher_rule.by_family.rapids_anomalies.accepted')} "
        f"Of the anomalies rows that do not meet the rule, {n(decomp.get('same_event_in_fasts_raw', 0))} are the fast-charger events the revision moved to the fasts publication "
        f"(they survive as duplicates of fasts rows) and {n(decomp.get('accepted_unexplained', 0))} are accepted here with no stated reason for their exclusion. "
        f"{cite('dft_publisher_rule.rapids_anomalies_not_meeting_rule.same_event_in_fasts_raw', 'dft_publisher_rule.rapids_anomalies_not_meeting_rule.accepted_unexplained')} "
        f"In the other direction, {n(rapids['meets_rule'])} rows of the rapids raw file meet the exclusion rule yet were published as clean. "
        f"{cite('dft_publisher_rule.by_family.rapids.meets_rule')}",
        "",
        "**Why it matters.** Anyone who reproduces the publisher's figures from the raw file and the stated rule will not get the publisher's numbers, "
        "and anyone who trusts the anomalies file as 'the bad rows' will discard thousands of ordinary sessions.",
        "",
        "**What I would tell the decision-maker.** Treat the publisher's split as a label, not a rule: keep every row, carry the label as a flag, "
        "and apply one explicit session rule of your own (here: energy above zero and more than three minutes) so the exclusion is reproducible.",
        "",
        "**What would change my mind.** A published methodology note listing the other exclusion criteria (incomplete records, events from other schemes) "
        "would explain the unexplained rows; the reports mention such criteria without counts.",
        "",
        "## 3. Utilization depends on how ports are counted, by up to about a third of its value",
        "",
        "**Period.** Each source's own period (table above); no cross-source comparison.",
        "",
    ]
    for key, label in (
        ("boulder__connected", "Boulder, connected-time"),
        ("boulder__charging", "Boulder, charging-time"),
        ("cary__charging", "Cary, charging-time"),
        ("dft_2017__connected", "DfT 2017, connected-time"),
    ):
        r = ur.get(key)
        if not r:
            continue
        lines.append(
            f"- **{label} utilization** is {pct(r['production'], 2)} under the production port count (the larger of two lower bounds, so at or below every single definition), "
            f"and ranges from {pct(r['min'], 2)} ({r['min_definition']}) to {pct(r['max'], 2)} ({r['max_definition']}) across the pure definitions. "
            f"{cite(f'utilization_ranges.{key}.production', f'utilization_ranges.{key}.min', f'utilization_ranges.{key}.max')}"
        )
    over = a["station_days_over_100pct_production"]
    lines += [
        "",
        f"Under the production port count, {n(over.get('dft_2017', 0))} DfT station-days and {n(over.get('boulder', 0))} Boulder station-day{'' if over.get('boulder', 0) == 1 else 's'} exceed full utilization: "
        f"days on which the inferred port count is lower than what the sessions imply. "
        f"{cite('station_days_over_100pct_production.dft_2017', 'station_days_over_100pct_production.boulder')}",
        "",
        "**Why it matters.** A utilization figure quoted without its denominator definition is not comparable with any other, and the swing here is "
        "larger than most year-on-year changes an operator would act on.",
        "",
        "**What I would tell the decision-maker.** Ask for the port-count method and the over-100% count with every utilization figure; treat the "
        "inferred figures as an upper bound on utilization (ports are a lower bound) and use the spread across definitions as the error bar.",
        "",
        "**What would change my mind.** An inventory of ports per station would replace the inference and collapse the range.",
        "",
        "## What is deliberately not a finding",
        "",
        f"- DfT sessions with no charge-point id ({n(unknown['unknown_station_sessions'])} sessions, {n(unknown['unknown_station_kwh'])} kWh) are in the totals but have no station, so no capacity or utilization is stated for them. "
        f"{cite('unknown_station.dft_2017.unknown_station_sessions', 'unknown_station.dft_2017.unknown_station_kwh')}",
        "- No growth-by-operator finding: each source is one operator and the periods differ; growth within Boulder or Cary would mostly reflect stations being added, which the data records only as first sessions.",
        "- No time-of-day finding beyond the blocking-idle hours: the hour profiles of session starts are in docs/PROFILE.md and do not change a decision on their own.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--db", type=Path, default=Path(".duckdb/dev.duckdb"))
    p.add_argument("--out", type=Path, default=ARTIFACTS_DIR / "findings")
    p.add_argument("--check", action="store_true")
    p.add_argument(
        "--render",
        action="store_true",
        help="re-render docs/FINDINGS.md from the latest artifact without recomputing",
    )
    a = p.parse_args(argv)
    if a.render:
        OUT.write_text(render(latest("findings")), encoding="utf-8")
        print(f"rendered {OUT.relative_to(REPO_ROOT)} from the latest findings artifact")
        return 0
    if a.check:
        art = latest("findings")
        if OUT.read_text(encoding="utf-8") != render(art):
            print("docs/FINDINGS.md is stale; run python scripts/findings.py")
            return 1
        print("ok: docs/FINDINGS.md matches the findings artifact")
        return 0
    rid = run_id()
    con = duckdb.connect(str(a.db), read_only=True)
    try:
        art = compute(
            con, latest("sensitivity"), latest("silver"), rid=rid, code_commit=git_commit()
        )
    finally:
        con.close()
    a.out.mkdir(parents=True, exist_ok=True)
    path = a.out / f"{rid}.json"
    path.write_text(json.dumps(art, indent=2, sort_keys=True, default=str) + "\n")
    (a.out / "latest.json").write_text(json.dumps({"run_id": rid, "path": path.name}) + "\n")
    OUT.write_text(render(art), encoding="utf-8")
    print(f"wrote {path} and {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
