#!/usr/bin/env python
"""Render docs/PROFILE.md and the inventory block of docs/DATA_SOURCES.md from the newest
profile artifact. Every number in those documents comes from the artifact and carries its
run id; nothing is typed by hand.

    python scripts/render_profile.py [--artifact artifacts/profile/<run_id>.json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ev_charging_data_unified_schema.config import ARTIFACTS_DIR, REPO_ROOT  # noqa: E402

INVENTORY_START = "<!-- generated:inventory start -->"
INVENTORY_END = "<!-- generated:inventory end -->"
SOURCE_TITLES = {
    "cary": "Cary, NC",
    "boulder": "Boulder, CO",
    "dundee": "Dundee, UK",
    "palo_alto": "Palo Alto, CA",
}


def latest_artifact(out_dir: Path) -> Path:
    latest = json.loads((out_dir / "latest.json").read_text())
    return out_dir / latest["path"]


def pct(num: int | None, den: int | None) -> str:
    if num is None or not den:
        return "n/a"
    return f"{100 * num / den:.2f}%"


def fmt(v: Any) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:,.3f}".rstrip("0").rstrip(".")
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(fmt(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def inventory_rows(art: dict[str, Any]) -> list[list[Any]]:
    rows = []
    for name, src in art["sources"].items():
        if not src.get("available"):
            rows.append(
                [SOURCE_TITLES.get(name, name), "(none downloaded)", "n/a", "n/a", "n/a", "n/a"]
            )
            continue
        for f in src["files"]:
            dl = f.get("download") or {}
            rows.append(
                [
                    SOURCE_TITLES.get(name, name),
                    "`" + f["path"].split("/")[-1] + "`",
                    dl.get("retrieved_at", "n/a"),
                    f["bytes"],
                    f["rows"],
                    "`" + f["sha256"][:16] + "…`",
                ]
            )
    return rows


def render_inventory(art: dict[str, Any]) -> str:
    body = table(
        ["Source", "File", "Retrieved (UTC)", "Bytes", "Data rows", "SHA-256 (prefix)"],
        inventory_rows(art),
    )
    return (
        f"{INVENTORY_START}\n"
        f"_Generated by `scripts/render_profile.py` from `artifacts/profile/{art['run_id']}.json` "
        f"(code commit `{art['code_commit'][:12]}`); full hashes are in the artifact._\n\n{body}\n{INVENTORY_END}"
    )


def column_table(f: dict[str, Any]) -> str:
    rows = []
    for c in f["column_profiles"]:
        extra = ""
        if c["inferred_type"] in ("integer", "decimal"):
            extra = f"min {fmt(c['min'])}, max {fmt(c['max'])}, zeros {fmt(c['zero_count'])}"
        elif c["inferred_type"] in ("datetime", "date"):
            extra = f"{c['min']} → {c['max']}"
            ev = c.get("day_first_evidence")
            if ev:
                extra += f"; day-first evidence: {ev['verdict']} ({fmt(ev['first_field_gt_12'])} values with first field > 12)"
        elif c["inferred_type"] == "duration_hms":
            extra = f"{fmt(c['min_minutes'])} → {fmt(c['max_minutes'])} min, zeros {fmt(c['zero_count'])}, over 24 h {fmt(c['over_24h_count'])}"
        rows.append(
            [
                f"`{c['name']}`",
                c["inferred_type"] + (f" ({c['pattern']})" if c.get("pattern") else ""),
                pct(c["null_or_blank"], c["rows"]),
                c["distinct"],
                extra,
            ]
        )
    return table(["Column", "Inferred type", "Null / blank", "Distinct", "Range and notes"], rows)


def hist_line(h: dict[str, int], width: int = 24) -> str:
    items = sorted(h.items(), key=lambda kv: int(kv[0]))
    if not items:
        return ""
    mx = max(v for _, v in items) or 1
    return "\n".join(
        f"    {int(k):>2}h {'█' * max(1, round(width * v / mx)):<{width}} {v:,}" for k, v in items
    )


def render_source(name: str, src: dict[str, Any]) -> str:
    title = SOURCE_TITLES.get(name, name)
    if not src.get("available"):
        return f"## {title}\n\n**Not profiled.** {src.get('reason', 'no file available')}\n"
    a = src["answers"]
    out = [f"## {title}\n"]
    out.append("### Files\n")
    out.append(
        table(
            ["File", "Bytes", "Data rows", "Exact duplicate rows", "Columns"],
            [
                [
                    f"`{f['path'].split('/')[-1]}`",
                    f["bytes"],
                    f["rows"],
                    f["exact_duplicate_rows"],
                    len(f["columns"]),
                ]
                for f in src["files"]
            ],
        )
    )
    if a.get("fully_blank_rows"):
        out.append(
            f"\nFully blank rows across files: {fmt(a['fully_blank_rows'])} (excluded from every count below)."
        )
    cov = a["coverage"]
    out.append(
        f"\nSessions start {cov['start_min']} → {cov['start_max']} (as published, before timezone handling). By year: "
        + ", ".join(f"{y}: {fmt(n)}" for y, n in cov["sessions_by_year"].items())
        + "."
    )
    if len(cov["files_by_start_range"]) > 1:
        out.append(
            "\n"
            + table(
                ["File", "Rows", "First start", "Last start"],
                [
                    [f"`{f}`", v["rows"], v["start_min"], v["start_max"]]
                    for f, v in cov["files_by_start_range"].items()
                ],
            )
        )

    out.append("\n### Columns (first file)\n")
    out.append(column_table(src["files"][0]))

    out.append("\n### The six questions\n")
    sid = a["session_id"]
    if sid["column"]:
        out.append(
            f"**Stable session id?** Yes: `{sid['column']}`. {fmt(sid['distinct'])} distinct over {fmt(sid['rows'])} rows; {fmt(sid['null_count'])} null; {fmt(sid['duplicate_ids_within_files'])} duplicated within a file; {fmt(sid['ids_in_more_than_one_file'])} ids appear in more than one file."
        )
    else:
        out.append(
            "**Stable session id?** No. No session identifier is published; the natural key is "
            + ", ".join(f"`{c}`" for c in a["overlap"]["natural_key"])
            + "."
        )
    ov = a["overlap"]
    line = f"\n**Overlapping or re-delivered files?** Exact duplicate rows: {fmt(ov['exact_duplicate_rows'])}; natural-key duplicates: {fmt(ov['natural_key_duplicate_rows'])}."
    if ov["keys_shared_between_files"]:
        line += (
            " Keys shared between files: "
            + "; ".join(f"{k}: {fmt(v)}" for k, v in ov["keys_shared_between_files"].items())
            + "."
        )
    if "delivery_blocks" in ov:
        b = ov["delivery_blocks"]["blocks"]
        line += (
            f" The single file holds {len(b)} concatenated deliveries (the per-delivery row id `ObjectID` restarts at 0 at rows "
            + ", ".join(fmt(x["first_row"]) for x in b)
            + "): "
        )
        line += (
            "; ".join(
                f"block {x['index']} has {fmt(x['rows'])} rows ({x['start_min'][:10]} → {x['start_max'][:10]}), {fmt(x['rows_with_key_in_last_block']) if x['rows_with_key_in_last_block'] is not None else 'n/a'} of them present in the last block, {fmt(x['natural_key_duplicates_within_block'])} natural-key duplicates inside the block, {fmt(x['iso_format_rows'])} rows in ISO timestamp format"
                for x in b
            )
            + "."
        )
    if "redelivery_diff" in ov:
        r = ov["redelivery_diff"]
        line += (
            f" Re-delivery pair `{r['files'][0]}` vs `{r['files'][1]}`: {fmt(r['ids_shared'])} shared ids, {fmt(r['ids_only_a'])} only in the first, {fmt(r['ids_only_b'])} only in the second; {fmt(r['shared_ids_with_any_differing_value'])} shared ids differ in at least one value (by column: "
            + ", ".join(f"{c} {fmt(v)}" for c, v in r["differing_by_column"].items() if v)
            + ")."
        )
    out.append(line)
    st = a["stations"]
    line = "\n**Station ids or only names?** "
    if st["station_id_column"]:
        line += f"Both: `{st['station_id_column']}` ({fmt(st['distinct_ids'])} distinct; forms: {', '.join(f'{k} {fmt(v)} rows' for k, v in st['id_forms'].items())}) and `{st['station_name_column']}` ({fmt(st['distinct_names'])} distinct). {fmt(st['names_with_multiple_ids'])} names carry more than one id (hub sites); {fmt(st['ids_with_multiple_names'])} ids appear under more than one name (moved or renamed)."
    else:
        line += f"Names only: `{st['station_name_column']}` ({fmt(st['distinct_names'])} distinct)."
        if st.get("site_key_column"):
            line += (
                f" `{st['site_key_column']}` gives {fmt(st['distinct_site_keys'])} distinct sites; names per site: "
                + ", ".join(
                    f"{k} name(s) at {fmt(v)} sites" for k, v in st["names_per_site_key"].items()
                )
                + "."
            )
    sp = st["sessions_per_station"]
    line += f" Sessions per station key: min {fmt(sp['min'])}, median {fmt(sp['median'])}, max {fmt(sp['max'])}; {fmt(sp['stations_under_30_sessions'])} keys have under 30 sessions."
    out.append(line)
    po = a["port"]
    line = "\n**Port or plug identifier?** " + (
        f"Yes: `{po['port_id_column']}`." if po["port_id_column"] else "No port identifier."
    )
    if po["port_type_column"]:
        line += (
            f" `{po['port_type_column']}` is a class, not an id: "
            + ", ".join(f"{k} {fmt(v)}" for k, v in po["port_type_values"].items())
            + "."
        )
    out.append(line)
    du = a["durations"]
    parts = []
    if du["charging_duration_column"]:
        parts.append(f"charging duration `{du['charging_duration_column']}`")
    if du["connected_duration_column"]:
        parts.append(f"connected duration `{du['connected_duration_column']}`")
    if du["connected_duration_derivable_from_start_end"]:
        parts.append(
            f"start and end (`{du['start_column']}`, `{du['end_column']}`) from which connected time is derivable"
        )
    else:
        parts.append(
            f"start only (`{du['start_column']}`); no end, so connected time is not derivable"
        )
    line = "\n**Which durations?** " + "; ".join(parts) + "."
    if "idle_share_of_connected_minutes" in du:
        line += f" Idle share of connected minutes (1 - charging / connected): {du['idle_share_of_connected_minutes']:.2%}."
    if "span_vs_recorded_duration" in du:
        s = du["span_vs_recorded_duration"]
        line += f" End - start versus `{s['compared_with']}` on {fmt(s['rows_compared'])} rows: within 2 min {fmt(s['within_2_min'])} ({pct(s['within_2_min'], s['rows_compared'])}); span longer by over 5 min {fmt(s['span_longer_by_over_5_min'])}; shorter {fmt(s['span_shorter_by_over_5_min'])}; one-hour gaps {fmt(s['one_hour_gap_rows'])}."
        top = sorted(s["one_hour_gap_by_month"].items(), key=lambda kv: -kv[1])[:4]
        if top:
            line += (
                " One-hour gaps by month, top: " + ", ".join(f"{m} {fmt(v)}" for m, v in top) + "."
            )
    out.append(line)
    im = a["implausible"]
    n = im["rows"]
    rows = [
        ["Energy zero", im["energy_zero"], pct(im["energy_zero"], n)],
        ["Energy null", im["energy_null"], pct(im["energy_null"], n)],
        ["Energy negative", im["energy_negative"], pct(im["energy_negative"], n)],
    ]
    if im["charging_minutes_zero"] is not None:
        rows += [
            [
                "Charging minutes zero",
                im["charging_minutes_zero"],
                pct(im["charging_minutes_zero"], n),
            ],
            [
                "Charging minutes null",
                im["charging_minutes_null"],
                pct(im["charging_minutes_null"], n),
            ],
            ["Charging over 24 h", im["charging_over_24h"], pct(im["charging_over_24h"], n)],
            [
                "Energy zero but charging minutes > 0",
                im["energy_zero_with_charging_minutes_over_0"],
                pct(im["energy_zero_with_charging_minutes_over_0"], n),
            ],
            [
                "Energy > 0 but charging minutes zero",
                im["energy_over_0_with_charging_minutes_zero"],
                pct(im["energy_over_0_with_charging_minutes_zero"], n),
            ],
        ]
    if im["connected_over_24h"] is not None:
        rows += [
            ["Connected over 24 h", im["connected_over_24h"], pct(im["connected_over_24h"], n)],
            [
                "Charging exceeds connected",
                im["charging_exceeds_connected"],
                pct(im["charging_exceeds_connected"], n),
            ],
        ]
    if "span_over_24h" in im:
        rows += [
            ["End - start over 24 h", im["span_over_24h"], pct(im["span_over_24h"], n)],
            ["End - start over 7 days", im["span_over_7d"], pct(im["span_over_7d"], n)],
            [
                "End before start (excluding 1970 sentinel)",
                im["end_before_start_excluding_sentinel"],
                pct(im["end_before_start_excluding_sentinel"], n),
            ],
            [
                "End is the 1970 epoch sentinel",
                im["end_is_1970_epoch_sentinel"],
                pct(im["end_is_1970_epoch_sentinel"], n),
            ],
            ["End equals start", im["end_equals_start"], pct(im["end_equals_start"], n)],
            ["End null or unparseable", im["end_null"], pct(im["end_null"], n)],
            [
                "Crosses local midnight",
                im["crosses_local_midnight"],
                pct(im["crosses_local_midnight"], n),
            ],
        ]
    out.append(
        f"\n**Zero-energy, over-24 h, end-before-start shares** (of {fmt(n)} non-blank rows):\n\n"
        + table(["Condition", "Rows", "Share"], rows)
    )
    if "implied_kw_quantiles" in im:
        q = im["implied_kw_quantiles"]
        line = f"\nImplied power (kWh / charging hours) quantiles: p50 {fmt(q['0.5'])}, p90 {fmt(q['0.9'])}, p99 {fmt(q['0.99'])}, p99.9 {fmt(q['0.999'])} kW."
        if "implied_kw_over_ceiling" in im:
            line += f" Rows above a {fmt(im['implied_kw_over_ceiling']['ceiling_kw'])} kW ceiling: {fmt(im['implied_kw_over_ceiling']['rows'])}."
        if "implied_kw_p50_by_port_type" in im:
            line += (
                " Median by port type: "
                + ", ".join(
                    f"{k} {fmt(v)} kW" for k, v in im["implied_kw_p50_by_port_type"].items()
                )
                + "."
            )
        out.append(line)

    tz = a["timezone"]
    out.append(
        f"\n### Timezone evidence\n\nAssumed station zone `{tz['assumed_zone']}`; published format `{tz['start_format']}`."
    )
    if "tz_label_values" in tz:
        out.append(
            "\nTimezone label values: "
            + ", ".join(f"{k} {fmt(v)}" for k, v in tz["tz_label_values"].items())
            + ". Label by start month (a label that says MDT in January is not a per-row offset):\n\n"
            + table(
                ["Month", *sorted(next(iter(tz["tz_label_by_start_month"].values())).keys())],
                [
                    [m, *[r.get(c, 0) for c in sorted(r.keys())]]
                    for m, r in sorted(
                        tz["tz_label_by_start_month"].items(), key=lambda kv: int(kv[0])
                    )
                ],
            )
        )
    if "dst_transition_gaps" in tz:
        out.append(
            f"\n{tz['dst_note']}:\n\n"
            + table(
                [
                    "Transition date",
                    "Sessions spanning 01:00-02:00",
                    "(end - start) - duration, minutes: count",
                ],
                [
                    [
                        d,
                        v["sessions_spanning_window"],
                        ", ".join(f"{g}: {c}" for g, c in v["gap_minutes_counts"].items()) or "-",
                    ]
                    for d, v in tz["dst_transition_gaps"].items()
                ],
            )
        )
    out.append(
        "\nStart hour histogram as published:\n\n```\n"
        + hist_line(tz["start_hour_histogram_as_published"])
        + "\n```"
    )
    if "start_hour_histogram_if_utc_converted_to_local" in tz:
        out.append(
            f"\n{tz['note']}. Converted to `{tz['assumed_zone']}`:\n\n```\n"
            + hist_line(tz["start_hour_histogram_if_utc_converted_to_local"])
            + "\n```"
        )

    if "observed_concurrency" in a:
        oc = a["observed_concurrency"]
        out.append(
            f"\n### Observed concurrency (capacity evidence)\n\nAfter natural-key deduplication, on {fmt(oc['sessions_used'])} sessions of at least {oc['min_session_minutes']} minutes, the maximum number of simultaneously open sessions per key (a lower bound on ports in service):"
        )
        for label in ("by_station_key", "by_site_key"):
            if label in oc:
                c = oc[label]
                out.append(
                    f"\n- by `{c['key']}` ({fmt(c['keys'])} keys): "
                    + ", ".join(f"max {k} at {fmt(v)} keys" for k, v in c["distribution"].items())
                    + ". Highest: "
                    + ", ".join(f"{k} = {v}" for k, v in c["top"].items())
                    + "."
                )
    if "charge_points_per_site" in a:
        c = a["charge_points_per_site"]
        out.append(
            f"\nCharge-point ids per site ({fmt(c['sites'])} sites): "
            + ", ".join(f"{k} id(s) at {fmt(v)} sites" for k, v in c["distribution"].items())
            + ". Largest: "
            + ", ".join(f"{k} = {v}" for k, v in c["top"].items())
            + "."
        )
    if "location_layer_match" in a:
        m = a["location_layer_match"]
        out.append(
            f"\nThe publisher's charge-point location layer ({fmt(m['features'])} features, {fmt(m['distinct_connector_ids'])} connector ids on {fmt(m['distinct_base_charge_point_ids'])} base charge-point ids) matches {fmt(m['usage_ids_found_in_layer'])} of the {fmt(m['usage_charge_point_ids'])} usage charge-point ids ({pct(m['usage_ids_found_in_layer'], m['usage_charge_point_ids'])}), covering {m['share_of_sessions_with_id_in_layer']:.2%} of sessions. It cannot supply port counts for this data."
        )

    pdata = a["personal_data"]
    out.append(
        "\n### Personal data\n\n"
        + (
            "User-level columns: " + ", ".join(f"`{c}`" for c in pdata["user_level_columns"])
            if pdata["user_level_columns"]
            else "No user-level columns. Address, city, state and postal-code columns describe the station."
        )
        + " (docs/adr/0003-personal-data.md).\n"
    )
    return "\n".join(out)


def render_profile(art: dict[str, Any]) -> str:
    head = [
        "# Source profiles\n",
        f"_Generated by `scripts/render_profile.py` from `artifacts/profile/{art['run_id']}.json` (code commit `{art['code_commit'][:12]}`, generated {art['generated_at_utc']}). Every number on this page is read from that artifact; the artifact records each input file's sha256, byte size and row count and the definitions of every measure. Do not edit by hand._\n",
        "Raw files are git-ignored (docs/adr/0002-source-redistribution.md). Shares are of non-blank rows across all of a source's files before any deduplication unless stated.\n",
        "## Definitions\n",
        "\n".join(f"- **{k}**: {v}" for k, v in art["definitions"].items()) + "\n",
    ]
    body = [
        render_source(n, art["sources"][n])
        for n in ("cary", "boulder", "dundee", "palo_alto")
        if n in art["sources"]
    ]
    pa = art.get("palo_alto_unverified")
    if pa:
        body.append(
            f"\nUnverified Palo Alto column list ({pa['note']}): user-level "
            + ", ".join(f"`{c}`" for c in pa["user_level_columns"])
            + "; device-level "
            + ", ".join(f"`{c}`" for c in pa["device_level_columns"])
            + ".\n"
        )
    return "\n".join(head + body)


def splice_inventory(doc: str, block: str) -> str:
    pat = re.compile(re.escape(INVENTORY_START) + r".*?" + re.escape(INVENTORY_END), re.S)
    if not pat.search(doc):
        raise SystemExit("docs/DATA_SOURCES.md has no generated:inventory markers")
    return pat.sub(lambda _m: block, doc)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--artifact", type=Path, default=None)
    p.add_argument(
        "--check",
        action="store_true",
        help="fail if the rendered docs differ from the committed ones",
    )
    a = p.parse_args(argv)
    path = a.artifact or latest_artifact(ARTIFACTS_DIR / "profile")
    art = json.loads(path.read_text())
    profile_md = render_profile(art)
    ds_path = REPO_ROOT / "docs" / "DATA_SOURCES.md"
    ds_md = splice_inventory(ds_path.read_text(encoding="utf-8"), render_inventory(art))
    targets = {REPO_ROOT / "docs" / "PROFILE.md": profile_md, ds_path: ds_md}
    if a.check:
        stale = [
            str(t.relative_to(REPO_ROOT))
            for t, text in targets.items()
            if not t.exists() or t.read_text(encoding="utf-8") != text
        ]
        if stale:
            print(
                "stale rendered docs: "
                + ", ".join(stale)
                + "; run python scripts/render_profile.py"
            )
            return 1
        print("ok: rendered docs match the profile artifact")
        return 0
    for t, text in targets.items():
        t.write_text(text, encoding="utf-8")
        print(f"wrote {t.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
