#!/usr/bin/env python
"""Render docs/PROFILE.md and the inventory block of docs/DATA_SOURCES.md from the newest
profile artifact. Every number in those documents comes from the artifact and carries its
run id; nothing is typed by hand.

    python scripts/render_profile.py [--artifact artifacts/profile/<run_id>.json] [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ev_charging_data_unified_schema.config import ARTIFACTS_DIR, REPO_ROOT  # noqa: E402

INVENTORY_START = "<!-- generated:inventory start -->"
INVENTORY_END = "<!-- generated:inventory end -->"
SOURCE_TITLES = {
    "cary": "Cary, NC",
    "boulder": "Boulder, CO",
    "dft_2017": "UK DfT, Electric Chargepoint Analysis 2017",
}


def latest_artifact(out_dir: Path) -> Path:
    latest = json.loads((out_dir / "latest.json").read_text())
    return out_dir / latest["path"]


def pct(num: int | None, den: int | None) -> str:
    if num is None or not den:
        return "n/a"
    return f"{100 * num / den:.2f}%"


def fmt(v: Any) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, float):
        return f"{v:,.3f}".rstrip("0").rstrip(".")
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(fmt(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def kv(d: dict[str, Any], sep: str = ", ") -> str:
    return sep.join(f"{k} {fmt(v)}" for k, v in d.items())


def base(path: str) -> str:
    return "`" + path.split("/")[-1] + "`"


# --- inventory ---------------------------------------------------------------------------------


def inventory_rows(art: dict[str, Any]) -> list[list[Any]]:
    rows = []
    for name, src in art["sources"].items():
        title = SOURCE_TITLES.get(name, name)
        if not src.get("available"):
            rows.append([title, "(none downloaded)", "n/a", "n/a", "n/a", "n/a"])
            continue
        for f in src["files"]:
            dl = f.get("download") or {}
            rows.append(
                [
                    title,
                    base(f["path"]),
                    dl.get("retrieved_at", "n/a"),
                    f["bytes"],
                    f["rows"],
                    "`" + f["sha256"][:16] + "…`",
                ]
            )
    return rows


def render_inventory(art: dict[str, Any]) -> str:
    body = table(
        ["Source", "File", "Retrieved (UTC)", "Bytes", "Data rows", "SHA-256 (prefix)"],
        inventory_rows(art),
    )
    return (
        f"{INVENTORY_START}\n"
        f"_Generated by `scripts/render_profile.py` from `artifacts/profile/{art['run_id']}.json` "
        f"(code commit `{art['code_commit'][:12]}`); full hashes are in the artifact._\n\n"
        f"{body}\n{INVENTORY_END}"
    )


# --- per-source sections -----------------------------------------------------------------------


def column_table(f: dict[str, Any]) -> str:
    rows = []
    for c in f["column_profiles"]:
        extra = ""
        if c["inferred_type"] in ("integer", "decimal"):
            extra = f"min {fmt(c['min'])}, max {fmt(c['max'])}, zeros {fmt(c['zero_count'])}"
        elif c["inferred_type"] in ("datetime", "date"):
            extra = f"{c['min']} → {c['max']}"
            ev = c.get("day_first_evidence")
            if ev:
                extra += (
                    f"; day-first evidence: {ev['verdict']} "
                    f"({fmt(ev['first_field_gt_12'])} values with first field > 12)"
                )
        elif c["inferred_type"] == "duration_hms":
            extra = (
                f"{fmt(c['min_minutes'])} → {fmt(c['max_minutes'])} min, zeros {fmt(c['zero_count'])}, "
                f"over 24 h {fmt(c['over_24h_count'])}"
            )
        typ = c["inferred_type"] + (f" ({c['pattern']})" if c.get("pattern") else "")
        rows.append(
            [f"`{c['name']}`", typ, pct(c["null_or_blank"], c["rows"]), c["distinct"], extra]
        )
    return table(["Column", "Inferred type", "Null / blank", "Distinct", "Range and notes"], rows)


def hist_line(h: dict[str, int], width: int = 24) -> str:
    items = sorted(h.items(), key=lambda kv_: int(kv_[0]))
    if not items:
        return ""
    mx = max(v for _, v in items) or 1
    return "\n".join(
        f"    {int(k):>2}h {'█' * max(1, round(width * v / mx)):<{width}} {v:,}" for k, v in items
    )


def files_section(src: dict[str, Any], a: dict[str, Any]) -> list[str]:
    out = ["### Files\n"]
    out.append(
        table(
            ["File", "Family", "Bytes", "Data rows", "Exact duplicate rows", "Columns"],
            [
                [
                    base(f["path"]),
                    f.get("family") or "-",
                    f["bytes"],
                    f["rows"],
                    f["exact_duplicate_rows"],
                    len(f["columns"]),
                ]
                for f in src["files"]
            ],
        )
    )
    if any(f.get("na_token_counts") for f in src["files"]):
        out.append(
            "\nLiteral `NA` tokens (treated as null in every count below): "
            + "; ".join(
                f"{base(f['path'])}: {kv(f['na_token_counts'])}"
                for f in src["files"]
                if f.get("na_token_counts")
            )
            + "."
        )
    if len(src["files"]) > 1:
        heads = {base(f["path"]): f["columns"] for f in src["files"]}
        first = next(iter(heads.values()))
        diffs = []
        for n, cols in heads.items():
            if cols == first:
                continue
            added = [c for c in cols if c not in first]
            lacking = [c for c in first if c not in cols]
            parts = []
            if added:
                parts.append("adds " + ", ".join(f"`{c}`" for c in added))
            if lacking:
                parts.append("lacks " + ", ".join(f"`{c}`" for c in lacking))
            if not parts:
                parts.append("same columns in a different order")
            diffs.append(f"{n}: " + "; ".join(parts))
        out.append(
            "\nHeader differences versus the first file: "
            + ("; ".join(diffs) if diffs else "none")
            + "."
        )
    if a.get("fully_blank_rows"):
        out.append(
            f"\nFully blank rows across files: {fmt(a['fully_blank_rows'])} (excluded from every count below)."
        )
    cov = a["coverage"]
    out.append(
        f"\nSessions start {cov['start_min']} → {cov['start_max']} (as published, before timezone handling). By year: "
        + kv(cov["sessions_by_year"], ", ").replace(" ", ": ", 0)
        + "."
    )
    if len(cov["files_by_start_range"]) > 1:
        out.append(
            "\n"
            + table(
                ["File", "Rows", "First start", "Last start"],
                [
                    [f"`{f}`", v["rows"], v["start_min"], v["start_max"]]
                    for f, v in cov["files_by_start_range"].items()
                ],
            )
        )
    return out


def questions_section(a: dict[str, Any]) -> list[str]:
    out = ["\n### The six questions\n"]
    sid = a["session_id"]
    if sid["column"]:
        out.append(
            f"**Stable session id?** `{sid['column']}` is published: {fmt(sid['distinct'])} distinct over "
            f"{fmt(sid['rows'])} rows; {fmt(sid['null_count'])} null; {fmt(sid['duplicate_ids_within_files'])} rows "
            f"repeat an id inside one file; {fmt(sid['ids_in_more_than_one_file'])} ids appear in more than one file."
        )
    else:
        out.append(
            "**Stable session id?** No. No session identifier is published; the natural key is "
            + ", ".join(f"`{c}`" for c in a["overlap"]["natural_key"])
            + "."
        )
    ov = a["overlap"]
    line = (
        f"\n**Overlapping or re-delivered files?** Exact duplicate rows: {fmt(ov['exact_duplicate_rows'])}; "
        f"natural-key duplicates: {fmt(ov['natural_key_duplicate_rows'])} (key: "
        + ", ".join(f"`{c}`" for c in ov["natural_key"])
        + ")."
    )
    if ov["keys_shared_between_files"]:
        line += (
            " Keys shared between files: "
            + "; ".join(f"{k}: {fmt(v)}" for k, v in ov["keys_shared_between_files"].items())
            + "."
        )
    if "delivery_blocks" in ov:
        b = ov["delivery_blocks"]["blocks"]
        line += (
            f" The single file holds {len(b)} concatenated deliveries (the per-delivery row id restarts at 0 at rows "
            + ", ".join(fmt(x["first_row"]) for x in b)
            + "): "
        )
        line += (
            "; ".join(
                f"block {x['index']} has {fmt(x['rows'])} rows ({x['start_min'][:10]} → {x['start_max'][:10]}), "
                f"{fmt(x['rows_with_key_in_last_block']) if x['rows_with_key_in_last_block'] is not None else 'n/a'} of them "
                f"present in the last block, {fmt(x['natural_key_duplicates_within_block'])} natural-key duplicates inside "
                f"the block, {fmt(x['iso_format_rows'])} rows in ISO timestamp format"
                for x in b
            )
            + "."
        )
    if "natural_key_conflicts" in ov:
        c = ov["natural_key_conflicts"]
        line += (
            f" Natural-key conflicts: {fmt(c['groups'])} groups; "
            f"{fmt(c['groups_where_one_row_has_zero_charging_and_zero_energy'])} contain a zero-charging, zero-energy row; "
            f"{fmt(c['groups_where_rows_differ_in_energy'])} differ in energy. {c['note']}."
        )
    out.append(line)

    st = a["stations"]
    line = "\n**Station ids or only names?** "
    if st["station_id_column"]:
        line += (
            f"Ids: `{st['station_id_column']}` ({fmt(st['distinct_ids'])} distinct, {fmt(st['null_ids'])} null; forms: "
            f"{kv({k: v for k, v in st['id_forms'].items()})} rows)."
        )
        if st.get("station_name_column"):
            line += f" Names: `{st['station_name_column']}` ({fmt(st['distinct_names'])} distinct)."
        if st.get("grouping_column_for_the_two_counts_above"):
            g = st["grouping_column_for_the_two_counts_above"]
            line += (
                f" Grouped by `{g}`: {fmt(st['names_with_multiple_ids'])} groups carry more than one id; "
                f"{fmt(st['ids_with_multiple_names'])} ids appear under more than one group."
            )
    else:
        line += f"Names only: `{st['station_name_column']}` ({fmt(st['distinct_names'])} distinct)."
    if st.get("site_key_column"):
        line += (
            f" `{st['site_key_column']}` gives {fmt(st['distinct_site_keys'])} distinct sites; station keys per site: "
            + ", ".join(f"{k} at {fmt(v)} sites" for k, v in st["names_per_site_key"].items())
            + "."
        )
    sp = st["sessions_per_station"]
    line += (
        f" Sessions per station key: min {fmt(sp['min'])}, median {fmt(sp['median'])}, max {fmt(sp['max'])}; "
        f"{fmt(sp['stations_under_30_sessions'])} keys have under 30 sessions."
    )
    out.append(line)

    po = a["port"]
    line = "\n**Port or plug identifier?** " + (
        f"Yes: `{po['port_id_column']}`." if po["port_id_column"] else "No port identifier."
    )
    if po.get("port_id_values"):
        line += (
            f" Values: {kv(po['port_id_values'])}. Rows with a null port id: {fmt(po['rows_with_null_port_id'])}. "
            "Distinct port ids per station id: "
            + ", ".join(f"{k} at {fmt(v)} stations" for k, v in po["ports_per_station_id"].items())
            + "."
        )
    if po["port_type_column"]:
        line += f" `{po['port_type_column']}` is a class, not an id: {kv(po['port_type_values'])}."
    out.append(line)

    du = a["durations"]
    parts = []
    if du["charging_duration_column"]:
        parts.append(f"charging duration `{du['charging_duration_column']}`")
    if du["connected_duration_column"]:
        parts.append(f"published plug-in duration `{du['connected_duration_column']}`")
    if du["connected_duration_derivable_from_start_end"]:
        parts.append(
            f"start and end (`{du['start_column']}`, `{du['end_column']}`) from which connected time is computed"
        )
    else:
        parts.append(
            f"start only (`{du['start_column']}`); no end, so connected time is not derivable"
        )
    line = (
        f"\n**Which durations?** Availability class `{du.get('availability', 'n/a')}`: "
        + "; ".join(parts)
        + "."
    )
    if du.get("connected_duration_unit_by_file"):
        line += (
            " Published duration unit by file: "
            + ", ".join(f"`{f}` {u}" for f, u in du["connected_duration_unit_by_file"].items())
            + " (files not listed have no duration column)."
        )
    if "idle_share_of_connected_minutes" in du:
        line += f" Idle share of connected minutes (1 - charging / connected): {du['idle_share_of_connected_minutes']:.2%}."
    if "span_vs_recorded_duration" in du:
        s = du["span_vs_recorded_duration"]
        line += (
            f" End - start versus `{s['compared_with']}` on {fmt(s['rows_compared'])} rows: within 2 min "
            f"{fmt(s['within_2_min'])} ({pct(s['within_2_min'], s['rows_compared'])}); span longer by over 5 min "
            f"{fmt(s['span_longer_by_over_5_min'])}; shorter {fmt(s['span_shorter_by_over_5_min'])}; one-hour gaps "
            f"{fmt(s['one_hour_gap_rows'])}."
        )
        top = sorted(s["one_hour_gap_by_month"].items(), key=lambda kv_: -kv_[1])[:4]
        if top:
            line += (
                " One-hour gaps by month, top: " + ", ".join(f"{m} {fmt(v)}" for m, v in top) + "."
            )
    out.append(line)

    im = a["implausible"]
    n = im["rows"]

    def row(label: str, key: str) -> list[Any]:
        return [label, im[key], pct(im[key], n)]

    rows = [
        row("Energy zero", "energy_zero"),
        row("Energy null", "energy_null"),
        row("Energy negative", "energy_negative"),
    ]
    if im.get("charging_minutes_zero") is not None:
        rows += [
            row("Charging minutes zero", "charging_minutes_zero"),
            row("Charging minutes null", "charging_minutes_null"),
            row("Charging over 24 h", "charging_over_24h"),
            row("Energy zero but charging minutes > 0", "energy_zero_with_charging_minutes_over_0"),
            row("Energy > 0 but charging minutes zero", "energy_over_0_with_charging_minutes_zero"),
        ]
    if im.get("connected_over_24h") is not None:
        rows += [
            row("Published plug-in duration zero", "connected_minutes_zero"),
            row("Published plug-in duration over 24 h", "connected_over_24h"),
        ]
    if im.get("charging_exceeds_connected") is not None:
        rows.append(row("Charging exceeds connected", "charging_exceeds_connected"))
    if "span_over_24h" in im:
        rows += [
            row("End - start over 24 h", "span_over_24h"),
            row("End - start over 7 days", "span_over_7d"),
            row(
                "End before start (excluding 1970 sentinel)", "end_before_start_excluding_sentinel"
            ),
            row("End is the 1970 epoch sentinel", "end_is_1970_epoch_sentinel"),
            row("End equals start", "end_equals_start"),
            row("End null or unparseable", "end_null"),
            row("Crosses local midnight", "crosses_local_midnight"),
            row("Crosses a year boundary", "crosses_year_boundary"),
        ]
    out.append(
        f"\n**Zero-energy, over-24 h, end-before-start shares** (of {fmt(n)} non-blank rows; energy minimum {fmt(im.get('energy_min'))}):\n\n"
        + table(["Condition", "Rows", "Share"], rows)
    )
    if "implied_kw_quantiles" in im:
        q = im["implied_kw_quantiles"]
        basis = im.get("implied_kw_basis", "charging_minutes").replace("_minutes", " hours")
        line = (
            f"\nImplied power (kWh / {basis}) quantiles: p50 {fmt(q['0.5'])}, p90 {fmt(q['0.9'])}, "
            f"p99 {fmt(q['0.99'])}, p99.9 {fmt(q['0.999'])} kW."
        )
        if "implied_kw_over_ceiling" in im:
            line += f" Rows above a {fmt(im['implied_kw_over_ceiling']['ceiling_kw'])} kW ceiling: {fmt(im['implied_kw_over_ceiling']['rows'])}."
        if "implied_kw_p50_by_port_type" in im:
            line += (
                " Median by port type: "
                + ", ".join(
                    f"{k} {fmt(v)} kW" for k, v in im["implied_kw_p50_by_port_type"].items()
                )
                + "."
            )
        out.append(line)
    tp = a.get("time_parsing", {})
    shapes = [f"{k}: {kv(v)}" for k, v in tp.items() if isinstance(v, dict)]
    if shapes:
        out.append(
            "\nTimestamp shapes: "
            + "; ".join(shapes)
            + f". Parse failures: start {fmt(tp.get('start_parse_failures'))}, end {fmt(tp.get('end_parse_failures'))}."
        )
    return out


def timezone_section(a: dict[str, Any]) -> list[str]:
    tz = a["timezone"]
    out = [
        f"\n### Timezone evidence\n\nAssumed station zone `{tz['assumed_zone']}`; published format `{tz['start_format']}`."
    ]
    if "seasonal_shift" in tz:
        s = tz["seasonal_shift"]
        out.append(
            f"\nSeasonal shift of the raw-hour profile (amendment c): circular mean raw start hour in summer (DST, "
            f"{fmt(s['summer_dst']['rows'])} rows) {fmt(s['summer_dst']['circular_mean_raw_hour'])}, in winter "
            f"({fmt(s['winter_std']['rows'])} rows) {fmt(s['winter_std']['circular_mean_raw_hour'])}; summer minus winter "
            f"{fmt(s['summer_minus_winter_mean_raw_hour'])} hours. Reading: {s['reading']}."
        )
    if "tz_label_values" in tz:
        months = sorted(tz["tz_label_by_start_month"].items(), key=lambda kv_: int(kv_[0]))
        labels = sorted({c for _, r in months for c in r})
        out.append(
            f"\nTimezone label values: {kv(tz['tz_label_values'])}. Label by start month (a label that says MDT in "
            "January is not a per-row offset):\n\n"
            + table(["Month", *labels], [[m, *[r.get(c, 0) for c in labels]] for m, r in months])
        )
    if "dst_transition_gaps" in tz:
        out.append(
            f"\n{tz['dst_note']}:\n\n"
            + table(
                [
                    "Transition date",
                    "Sessions spanning 01:00-02:00",
                    "(end - start) - duration, minutes: count",
                ],
                [
                    [
                        d,
                        v["sessions_spanning_window"],
                        ", ".join(f"{g}: {c}" for g, c in v["gap_minutes_counts"].items()) or "-",
                    ]
                    for d, v in tz["dst_transition_gaps"].items()
                ],
            )
        )
    out.append(
        "\nStart hour histogram as published:\n\n```\n"
        + hist_line(tz["start_hour_histogram_as_published"])
        + "\n```"
    )
    if "start_hour_histogram_if_utc_converted_to_local" in tz:
        out.append(
            f"\n{tz['note']}. Converted to `{tz['assumed_zone']}`:\n\n```\n"
            + hist_line(tz["start_hour_histogram_if_utc_converted_to_local"])
            + "\n```"
        )
    return out


def capacity_section(a: dict[str, Any]) -> list[str]:
    out: list[str] = []
    if "observed_concurrency" in a:
        oc = a["observed_concurrency"]
        out.append(
            f"\n### Observed concurrency (capacity evidence)\n\nAfter natural-key deduplication, on {fmt(oc['sessions_used'])} "
            f"sessions of at least {oc['min_session_minutes']} minutes, the maximum number of simultaneously open sessions "
            "per key (a lower bound on ports in service):"
        )
        for label in ("by_station_key", "by_site_key"):
            if label in oc:
                c = oc[label]
                out.append(
                    f"\n- by `{c['key']}` ({fmt(c['keys'])} keys): "
                    + ", ".join(f"max {k} at {fmt(v)} keys" for k, v in c["distribution"].items())
                    + ". Highest: "
                    + ", ".join(f"{k} = {v}" for k, v in c["top"].items())
                    + "."
                )
        if "days_at_level" in oc:
            d = oc["days_at_level"]
            levels = sorted({int(k) for h in d["robust_max_histogram_by_n"].values() for k in h})
            out.append(
                f"\nRobust max by `{d['key']}` (amendment f): {d['note']}. Histogram of the robust max over keys, by N:\n\n"
                + table(
                    ["N days", *[f"max {k}" for k in levels]],
                    [
                        [n, *[h.get(str(k), 0) for k in levels]]
                        for n, h in sorted(
                            d["robust_max_histogram_by_n"].items(), key=lambda kv_: int(kv_[0])
                        )
                    ],
                )
                + f"\n\nKeys whose plain max exceeds the robust max at N = 5: {fmt(d['keys_where_plain_max_exceeds_robust_max_n5'])}. "
                "Days-at-level quantiles (p10 / p50 / p90) per level: "
                + "; ".join(
                    f"level {lvl}: " + " / ".join(fmt(v) for v in q.values())
                    for lvl, q in d["days_at_level_quantiles"].items()
                )
                + "."
            )
        if "inter_session_gaps" in oc:
            g = oc["inter_session_gaps"]
            out.append(
                f"\nInter-session gaps by `{g['key']}` (amendment g), end of one session to start of the next, on "
                f"{fmt(g['gaps'])} gaps: quantiles (days) "
                + ", ".join(f"p{float(k) * 100:g} {fmt(v)}" for k, v in g["quantiles_days"].items())
                + ". Gaps longer than: "
                + ", ".join(f"{dd} d: {fmt(v)}" for dd, v in g["gaps_over_days"].items())
                + f". Keys with at least one gap over 30 days: {fmt(g['keys_with_a_gap_over_30d'])}."
            )
    if "charge_points_per_site" in a:
        c = a["charge_points_per_site"]
        out.append(
            f"\nStation ids per `{c.get('grouped_by', 'site')}` ({fmt(c['sites'])} groups): "
            + ", ".join(
                f"{k} id(s) at {fmt(v)} groups"
                for k, v in sorted(c["distribution"].items(), key=lambda kv_: int(kv_[0]))
            )
            + ". Largest: "
            + ", ".join(f"{k} = {v}" for k, v in c["top"].items())
            + "."
        )
    return out


def render_source(name: str, src: dict[str, Any]) -> str:
    title = SOURCE_TITLES.get(name, name)
    if not src.get("available"):
        return f"## {title}\n\n**Not profiled.** {src.get('reason', 'no file available')}\n"
    a = src["answers"]
    out = [f"## {title}\n"]
    out += files_section(src, a)
    out.append("\n### Columns (first file)\n")
    out.append(column_table(src["files"][0]))
    out += questions_section(a)
    out += timezone_section(a)
    out += capacity_section(a)
    pdata = a["personal_data"]
    out.append(
        "\n### Personal data\n\n"
        + (
            "User-level columns: " + ", ".join(f"`{c}`" for c in pdata["user_level_columns"])
            if pdata["user_level_columns"]
            else "No user-level columns. Address, city, state, postal-code and organisation-name columns describe the station or its funder."
        )
        + " (docs/adr/0003-personal-data.md).\n"
    )
    return "\n".join(out)


def render_profile(art: dict[str, Any]) -> str:
    head = [
        "# Source profiles\n",
        f"_Generated by `scripts/render_profile.py` from `artifacts/profile/{art['run_id']}.json` (code commit "
        f"`{art['code_commit'][:12]}`, generated {art['generated_at_utc']}). Every number on this page is read from that "
        "artifact; the artifact records each input file's sha256, byte size and row count and the definitions of every "
        "measure. Do not edit by hand._\n",
        "Raw files are git-ignored (docs/adr/0002-source-redistribution.md). Shares are of non-blank rows across all of a "
        "source's files before any deduplication unless stated.\n",
        "## Definitions\n",
        "\n".join(f"- **{k}**: {v}" for k, v in art["definitions"].items()) + "\n",
    ]
    body = [render_source(n, art["sources"][n]) for n in art["sources"]]
    return "\n".join(head + body)


def splice_inventory(doc: str, block: str) -> str:
    pat = re.compile(re.escape(INVENTORY_START) + r".*?" + re.escape(INVENTORY_END), re.S)
    if not pat.search(doc):
        raise SystemExit("docs/DATA_SOURCES.md has no generated:inventory markers")
    return pat.sub(lambda _m: block, doc)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--artifact", type=Path, default=None)
    p.add_argument(
        "--check",
        action="store_true",
        help="fail if the rendered docs differ from the committed ones",
    )
    a = p.parse_args(argv)
    path = a.artifact or latest_artifact(ARTIFACTS_DIR / "profile")
    art = json.loads(path.read_text())
    profile_md = render_profile(art)
    ds_path = REPO_ROOT / "docs" / "DATA_SOURCES.md"
    ds_md = splice_inventory(ds_path.read_text(encoding="utf-8"), render_inventory(art))
    targets = {REPO_ROOT / "docs" / "PROFILE.md": profile_md, ds_path: ds_md}
    if a.check:
        stale = [
            str(t.relative_to(REPO_ROOT))
            for t, text in targets.items()
            if not t.exists() or t.read_text(encoding="utf-8") != text
        ]
        if stale:
            print(
                "stale rendered docs: "
                + ", ".join(stale)
                + "; run python scripts/render_profile.py"
            )
            return 1
        print("ok: rendered docs match the profile artifact")
        return 0
    for t, text in targets.items():
        t.write_text(text, encoding="utf-8")
        print(f"wrote {t.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
