#!/usr/bin/env python
"""Render docs/CONTRACTS.md from ev_charging_data_unified_schema/data/contracts.py: every
declared column per source and family, alias maps, null tokens, duration units, and a diff
table across the DfT families. --check fails when the committed document is stale.

    python scripts/render_contracts.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ev_charging_data_unified_schema.config import REPO_ROOT  # noqa: E402
from ev_charging_data_unified_schema.data.contracts import CONTRACTS, FamilyContract  # noqa: E402

OUT = REPO_ROOT / "docs" / "CONTRACTS.md"


def table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(rows_) + " |" for rows_ in rows]
    return "\n".join(out)


def family_section(fam: FamilyContract) -> str:
    rows = [
        [f"`{c.name}`", c.logical_type, "yes" if c.required else "no", c.description]
        for c in fam.columns
    ]
    meta = [
        f"- file pattern: `{fam.file_pattern}`",
        "- aliases (published to canonical): "
        + (", ".join(f"`{k}` to `{v}`" for k, v in fam.aliases.items()) or "none"),
        "- null tokens: " + (", ".join(f"`{t}`" for t in fam.null_tokens) or "none"),
        "- published duration unit: " + (fam.duration_unit or "no duration column"),
    ]
    return (
        f"#### Family `{fam.family}`\n\n"
        + "\n".join(meta)
        + "\n\n"
        + table(["Column", "Logical type", "Required", "Description"], rows)
    )


def diff_table(families: tuple[FamilyContract, ...]) -> str:
    names: list[str] = []
    for fam in families:
        for c in fam.columns:
            if c.name not in names:
                names.append(c.name)
    for fam in families:
        for old in fam.aliases:
            if old not in names:
                names.append(old)
    rows = []
    for name in names:
        cells = []
        for fam in families:
            spec = fam.spec(name)
            if spec:
                unit = (
                    f", {fam.duration_unit}"
                    if name == "PluginDuration" and fam.duration_unit
                    else ""
                )
                cells.append(
                    f"{spec.logical_type}{unit}" + ("" if spec.required else " (optional)")
                )
            elif name in fam.aliases:
                cells.append(f"published as `{name}`, aliased to `{fam.aliases[name]}`")
            else:
                cells.append("absent")
        rows.append([f"`{name}`", *cells])
    return table(["Column", *[f"`{f.family}`" for f in families]], rows)


def render() -> str:
    out = [
        "# Source contracts\n",
        "_Generated by `scripts/render_contracts.py` from `ev_charging_data_unified_schema/data/contracts.py`. "
        "Do not edit by hand; `--check` runs in CI._\n",
        "A contract declares, per source and per file family, the columns the published file is expected to carry, "
        "the logical type of their values (everything lands as strings; the type is what the values parse as), "
        "whether each column is required, the alias map for renamed columns, the literal null tokens and the "
        "published duration unit. The drift policy that uses them is in docs/adr/0008-drift-policy.md.\n",
    ]
    for name, con in sorted(CONTRACTS.items()):
        out.append(f"## `{name}`\n")
        out.append(
            f"- station timezone: `{con.timezone}`\n- user-level columns (never selected by silver): "
            + (", ".join(con.user_level_columns) or "none")
            + "\n"
        )
        for fam in con.families:
            out.append(family_section(fam) + "\n")
        if len(con.families) > 1:
            out.append(f"### Columns across the `{name}` families\n")
            out.append(diff_table(con.families) + "\n")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--check", action="store_true")
    a = p.parse_args(argv)
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("docs/CONTRACTS.md is stale; run python scripts/render_contracts.py")
            return 1
        print("ok: docs/CONTRACTS.md matches the contracts")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
